version: 0.2

phases:
  pre_build:
    commands:
    - curl -O -L https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
    - unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip
    - mv terraform /usr/local/bin/
    - terraform --version
  build:
    commands:
    - ls
    - terraform init
    - terraform validate
    - terraform workspace new ${ENV}

  post_build:
    commands:
    - echo "validate sintax infra code completed successfully"
